### ISSUE TITLE
We've used 75% of included services for GitHub Actions

### ISSUE THREAD

**Issue by simenandre** [flexisoftorg/conf#30]
To continue using Actions & Packages uninterrupted, we need to update our spending limit.

![Skjermbilde 2023-04-17 kl  12 09 08](https://user-images.githubusercontent.com/3726815/232454461-90270729-4116-44f9-b0f5-a850700dd0f0.jpg)

**Comment by braaar** [comment]
Has this been resolved?

**Comment by simenandre** [comment]
Fixed!
