### ISSUE TITLE
Confirm new tenant flow

### ISSUE THREAD

**Issue by Xillians** [flexisoftorg/conf#482]
We need to verify the flow and required steps in order to set a new tenant up for flexisoft. The ideal world would be "create a new tenant in sanity, publish, end of flow". As things are right now, we need to find out what other steps need to be done (do the clients need to set up a DNS configuration? can we avoid that?)

**Comment by braaar** [comment]
We can avoid having the customer mess around with DNS if we use a predetermined domain. We could then set up everything automatically on deploy, including a DNS record for the subdomain for each customer, aka. inkassojentene.flexiportal.no, bjerk.flexiportal.no, etc.
